#!/bin/sh
# init a QtServer project in current directory

set -e
. "$(dirname $0)/libs.sh"

if [ ! "$(ls -a | grep '' -c)" -eq "2" ]; then
	warning "Current directory is not empty!"
	error "qspm init can only work in empty directory!"
fi

read_string()
{
	echo -n "$1: ($3) "
	read tmp
	if [ -z "$tmp" ]; then
		eval $2="$3"
	else
		eval $2="$tmp"
	fi
}

read_string "name" NAME $(basename $(readlink -f .) | sed 's/\.qs$//')
read_string "app/lib" KIND app
read_string "init git" INIT_GIT yes


TMP_DIR="$QSM_ROOT/templates/${KIND}"

if [ ! -d "$TMP_DIR" ]; then
	error "$TMP_DIR does not exists!"
fi

cp -rTv "$TMP_DIR" .

for f in $(find . -type f); do
	X=`cat $f | sed "s/QSM_NAME/$NAME/g"`
	F2=`echo "$f" | sed "s/QSM_NAME/$NAME/g"`
	rm "$f"
	echo "$X" > "$F2"
done

if [ "$INIT_GIT" = "yes" ]; then
	cp -rv "$TMP_DIR/.gitignore" .
	git init .
	git add . 
	git commit -m 'first commit'
fi
