#!/bin/sh
# build QtServer project

set -e
. "$(dirname $0)/libs.sh"

if [ ! -f "cmake/qsm.cmake" ]; then
	echo not in a qsm project
	exit
fi

dep_check()
{
	X=`cat qs_modules.cmake | grep qs_module | sed 's/.*(//; s/).*//; s/"//g' | awk '{print $1}'`
	for x in ${X}; do
		if [ ! -d "qs_modules/${x}" ]; then
			error "module ${x} does not exists, run \`qsm install\` first"
		fi
	done
}

dep_check

[ -d build ] || mkdir build
cd build

[ -f Makefile ] || cmake .. -D"QS_PATH=$QS_PATH"

make "$@"
